trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: 'ferozuddin/devops-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: SSH@0
  inputs:
    sshEndpoint: 'aws-ec2-ssh'
    runOptions: 'commands'
    commands: |
      docker pull yourdockerhubusername/devops-app
      docker stop devops-app || true
      docker rm devops-app || true
      docker run -d -p 5000:5000 --name devops-app yourdockerhubusername/devops-app
